### ISSUE TITLE
use same format for all documents under site/content/docs directory

### ISSUE THREAD

**Issue by serpilb** [OpenBMP/openbmp-www#17]
When i copied our docs from openbmp.org to snas.io, I didn't have enough time to make sure they are all formatted similarly. See http://localhost:3000/docs/use-case1/ vs http://localhost:3000/docs/architecture/. Can you go through all of them and make sure they have a similar format (I am working on the content).

**Comment by Matvey-Kuk** [comment]
@serpilb closed
