### ISSUE TITLE
Copy all openbmp.org md files to SNAS.io

### ISSUE THREAD

**Issue by serpilb** [OpenBMP/openbmp-www#20]
I copied some of the files from here:

https://github.com/OpenBMP/openbmp/tree/master/docs

to here:

https://www.snas.io/docs/

Can you check if I left out anything? For now all openbmp.org docs go here. And per previous issue I opened, they need to be formatted smilarly (I think all you need to do is add the title, type, and data on top and the "read more" line.

**Comment by Matvey-Kuk** [comment]
@serpilb closed
